<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Order.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../RabbitClientEasyNetQ/RabbitClientEasyNetQ.csproj" />
    <PackageReference Include="EasyNetQ" Version="8.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.*" />
  </ItemGroup>
</Project>
